{{- if .Values.mongodb }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-mongodb" .Release.Name }}
  labels:
    {{- include "config.labels" . | nindent 4 }}
stringData:
  CONNECT_STRING: {{ required "MongoDB connect string required" .Values.mongodb.connectString | quote }}
  USERNAME: {{ required "MongoDB username required" .Values.mongodb.username | quote }}
  PASSWORD: {{ required "MongoDB password required" .Values.mongodb.password | quote }}
  DATABASE_NAME: {{ default "ibmclouddb" .Values.mongodb.databaseName | quote }}
  {{- if .Values.mongodb.certificateBase64 }}
  CERTIFICATE_BASE64: {{ .Values.mongodb.certificateBase64 | quote }}
  {{- end }}
{{- end }}
