{{- if .Values.wml }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-wml" .Release.Name }}
  labels:
    {{- include "config.labels" . | nindent 4 }}
stringData:
  API_KEY: {{ required "WML API_KEY required" .Values.wml.apiKey | quote }}
  ENDPOINT: {{ required "WML endpoint required" .Values.wml.endpoint | quote }}
  IDENTITY_URL: {{ default "https://iam.cloud.ibm.com/identity/token" .Values.wml.identityUrl | quote }}
  VERSION: {{ default "2021-05-01" .Values.wml.version | quote }}
  DEFAULT_DEPLOYMENT_ID: {{ default "tax_withholding_v6a" .Values.wml.defaultDeploymentId | quote }}
  DEFAULT_DEPLOYMENT_FIELDS: {{ default "[]]" .Values.wml.defaultDeploymentFields | quote }}
{{- end }}
